import { Router } from 'express';
import Campaign from '../models/Campaign.js';
import { authenticate } from '../middleware/auth.js';
const router = Router();
router.use(authenticate);
router.get('/', async (req, res) => { try { res.json(await Campaign.findAll()); } catch(e) { res.status(500).json({error:e.message}); } });
router.get('/stats', async (req, res) => { try { res.json(await Campaign.getStats()); } catch(e) { res.status(500).json({error:e.message}); } });
router.get('/:id', async (req, res) => { try { const c = await Campaign.findById(req.params.id); c ? res.json(c) : res.status(404).json({error:'Not found'}); } catch(e) { res.status(500).json({error:e.message}); } });
router.post('/', async (req, res) => { try { res.status(201).json(await Campaign.create(req.body)); } catch(e) { res.status(500).json({error:e.message}); } });
router.patch('/:id', async (req, res) => { try { res.json(await Campaign.update(req.params.id, req.body)); } catch(e) { res.status(500).json({error:e.message}); } });
router.delete('/:id', async (req, res) => { try { await Campaign.delete(req.params.id); res.json({success:true}); } catch(e) { res.status(500).json({error:e.message}); } });
export default router;
